### ISSUE TITLE
Squiggly lines

### ISSUE THREAD

**Issue by bifurcation** [martinthomson/aasvg#15]
Would be nice to be able to render something like:

```
~~~~~>
```

**Comment by martinthomson** [comment]
Patches welcome.  I did some work to add double lines `====>`, but this is somewhat more tricky as you have to draw each squiggle independently.  (That is, you can't just say got from A to B with a squiggle, you have to effectively draw each curve.)

**Comment by bifurcation** [comment]
Wasn't too hard, just a little Bézier magic

https://github.com/martinthomson/aasvg/pull/16

**Comment by martinthomson** [comment]
You will observe that the new example has some spill-over on arrowheads from double lines and squiggly lines.  That's probably worth fixing eventually, but all that fit and finish stuff is very fiddly.  What you put together is very workable.  I've released a new version in case you want to use it in anger.

**Comment by bifurcation** [comment]
Filed #17
