### ISSUE TITLE
unjoined points for /\  frame

### ISSUE THREAD

**Issue by dkg** [martinthomson/aasvg#7]
I took a subset of a diagram from [RFC 9106](https://www.rfc-editor.org/rfc/rfc9106.html#name-indexing) and tried to pass it through aasvg to see what it would produce.

this is the source:

```
    slice 0    slice 1    slice 2    slice 3
    ___/\___   ___/\___   ___/\___   ___/\___
   /        \ /        \ /        \ /        \
  +----------+----------+----------+----------+
  |          |          |          |          | > lane 0
  +----------+----------+----------+----------+
```

It generated this:

![yyy](https://user-images.githubusercontent.com/66738/148659234-b5039842-b251-4aac-8e61-e7c5354c7f87.png)

(png version uploaded because github is justifiably scared of hosting arbitrary svg files)

I would have expected the `/\` parts to be connected to the neighboring lines, and to join together at the top vertex as well.  Instead, both symbols are free-floating.

**Comment by martinthomson** [comment]
Thanks @dkg,  I've fixed this by adding detection for this specific case.  I'm not 100% confident that it hasn't changed other things; it's not my code originally and the testing is still a little lean.  Let me know how this works out for you.  Release forthcoming soon.
