### ISSUE TITLE
example.txt no longer generates example.svg

### ISSUE THREAD

**Issue by dkg** [martinthomson/aasvg#8]
For the [debian packaging](https://tracker.debian.org/pkg/aasvg) i'm testing aasvg to ensure that it produces `example.svg` from `example.txt` (see for example the [build-time test](https://salsa.debian.org/debian/aasvg/-/blob/debian/sid/debian/rules#L21) and the [runtime test](https://salsa.debian.org/debian/aasvg/-/blob/debian/sid/debian/tests/simple) which both do the same thing).  this test fails as of 4694a38e366eaf0f2a000683108fb54a140eb5d2.

4694a38e366eaf0f2a000683108fb54a140eb5d2 claims that all it does is "remove translate transforms" but it actually also adds the `--source` argument.  that's a bit confusing, but i think the removal of the translate transforms is actually what is causing the breakage.

i could make the diff more sophisticated, e.g. by converting them both to PNGs and seeing whether there is in fact any difference, for example, something like:

 - convert the reference image and the re-generated image, e.g. using `gm convert example.{svg,png}` 
 - compare the resulting png's with `diffimg` from graphviz

(note: when i do this, the resulting image diff appears to be all-black, indicating no changes at the moment, so that's good!)

But if i do that for the test, then my choice of resolution and other parameters for the svg→png conversion tool might introduce spurious errors unrelated to the changes in aasvg, or mask changes in aasvg output.

or i could compare them with ImageMagick's `compare` utility which is supposed to return a distance metric between the images, and appears to think it can work on svg directly.  but it returns that the two files are different, even though the resulting output does not differ.

Can you keep `example.svg` up-to-date with `example.txt`?

**Comment by martinthomson** [comment]
This might just be skew, but I updated it shortly after fixing #7.  I see no difference now.  I'll add an npm test command and pre-commit to ensure that things work (or that example.svg is updated if the code changes).  I can use this to track that.

**Comment by martinthomson** [comment]
`npm test` should work now.

**Comment by dkg** [comment]
Thanks!  Looks like my problem was that the commits from 68feba537f7b40a1b32184f9b4cd5e2a00974046 on were not published here on github.  Now that they've been pushed i see the updated example. :+1: 

Looks like dcf222c3d2c9b6de89f7fb507caaa0d3207b4fbb changed the version to 0.1.8.  Would you be up for pushing a tag to github when a new version is released?  or should i be looking at the npmjs.org registry for new releases?

**Comment by dkg** [comment]
(i also note that `example.txt` and `example.svg` are not shipped in the version on npmjs.org, so for now i'll be building the debian package from git, not from the npm tarball)

**Comment by martinthomson** [comment]
Happy to push tags if that makes it easier for you.
